version: '3'
services:
  admin:
    container_name: 'tbizswap_admin'
    hostname: 'tbizswap_admin'
    image: 'huynhdn/tbizswap_admin_prod:1.0'
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:80